name: Automatic cucumber tests

on: push

permissions:
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up RVM
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install Google Chrome
      run: |
       chmod +x ./scripts/InstallChrome.sh
        ./scripts/InstallChrome.sh
    - name: Get dependencies
      run: bundle install
    - name: Run tests
      env:
        HEADLESS: true
      run: cucumber features --format junit --out test-results
    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        junit_files: test-results/*.xml